version: 0.2

phases:
  install:
    commands:
    - apt-get update
    - apt-get upgrade -y
    - apt install npm -y
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed 
artifacts:
  files:
    -*
