version: 0.2

phases:
  install:
    commands:
    - apt-get update
    - apt-get upgrade -y
    - curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
    - sudo apt install nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed 
artifacts:
  files:
    -*
